#!/usr/bin/env node

/**
 * Build script to bundle all fonts for pdfmake virtual file system
 * Generates src/reports/fonts/vfs_fonts_all.ts with:
 * - Standard Roboto fonts (from pdfmake's vfs_fonts.js)
 * - DejaVu Sans Mono fonts (for Unicode box-drawing characters)
 */

const fs = require('fs');
const path = require('path');

const fontsDir = path.join(__dirname, 'src', 'reports', 'fonts');
const outputFile = path.join(fontsDir, 'vfs_fonts_all.ts');
const pdfmakeVfsPath = path.join(__dirname, 'node_modules', 'pdfmake', 'build', 'vfs_fonts.js');

console.log('🔤 Bundling fonts for pdfmake...\n');

// Step 1: Extract Roboto fonts from pdfmake's vfs_fonts.js
console.log('📖 Reading pdfmake VFS fonts...');
const vfsFileContent = fs.readFileSync(pdfmakeVfsPath, 'utf-8');

// Extract the vfs object from the file (it's a CommonJS module)
// The file format is: var vfs = { "fontname": "base64data", ... };
const vfsMatch = vfsFileContent.match(/var\s+vfs\s*=\s*(\{[\s\S]*?\});/);
if (!vfsMatch) {
	console.error('❌ Could not extract VFS data from pdfmake vfs_fonts.js');
	process.exit(1);
}

const pdfmakeVfs = JSON.parse(vfsMatch[1]);

// Extract only the Roboto fonts we need
const robotoFonts = [
	'Roboto-Regular.ttf',
	'Roboto-Medium.ttf',
	'Roboto-Italic.ttf',
	'Roboto-MediumItalic.ttf'
];

const vfsEntries = {};
let totalSize = 0;

for (const fontName of robotoFonts) {
	if (!pdfmakeVfs[fontName]) {
		console.error(`❌ Font ${fontName} not found in pdfmake VFS`);
		process.exit(1);
	}

	const base64 = pdfmakeVfs[fontName];
	vfsEntries[fontName] = base64;

	// Calculate approximate size (base64 is ~4/3 of original size)
	const sizeKB = ((base64.length * 3 / 4) / 1024).toFixed(1);
	totalSize += (base64.length * 3 / 4);
	console.log(`✓ ${fontName} → ${sizeKB} KB`);
}

// Step 2: Convert our DejaVu Sans Mono TTF files to base64
console.log('\n📖 Converting DejaVu Sans Mono fonts...');

const monoFontFiles = {
	'DejaVuSansMono.ttf': 'DejaVuSansMono.ttf',
	'DejaVuSansMono-Oblique.ttf': 'DejaVuSansMono-Oblique.ttf'
};

for (const [filename, vfsName] of Object.entries(monoFontFiles)) {
	const fontPath = path.join(fontsDir, filename);

	if (!fs.existsSync(fontPath)) {
		console.error(`❌ Font file not found: ${fontPath}`);
		process.exit(1);
	}

	const fontBuffer = fs.readFileSync(fontPath);
	const base64 = fontBuffer.toString('base64');
	vfsEntries[vfsName] = base64;

	const sizeKB = (fontBuffer.length / 1024).toFixed(1);
	totalSize += fontBuffer.length;
	console.log(`✓ ${filename} → ${sizeKB} KB`);
}

console.log(`\n📦 Total font data: ${(totalSize / 1024).toFixed(1)} KB`);
console.log(`📦 Total fonts: ${Object.keys(vfsEntries).length}\n`);

// Generate TypeScript module
const tsContent = `/**
 * Virtual file system with all fonts for pdfmake
 * Auto-generated by build-fonts.js
 *
 * Includes:
 * - Roboto (Regular, Medium, Italic, MediumItalic) - Standard text
 * - DejaVu Sans Mono (Regular, Oblique) - Monospace with comprehensive Unicode support
 *   including box-drawing characters needed for ASCII tree visualizations in PDF reports.
 */

export const vfsFonts: { [filename: string]: string } = ${JSON.stringify(vfsEntries, null, '\t')};
`;

fs.writeFileSync(outputFile, tsContent);
console.log(`✓ Generated: ${outputFile}`);
console.log(`✓ Font VFS module ready for import\n`);
